name: 'composite action'
inputs:
  CACHE_DIR:
    description: 'aaa'
    required: true
    default: '${{ runner.temp }}/kubectl'  # $HOMEではなくrunner.tempを使用
  KUBECTL_VERSION:
    description: 'aaa'
    required: true
    default: 'v1.22.17'

runs:
  using: 'composite'
  steps:
    - name: Create cache directory
      run: mkdir -p ${{ inputs.CACHE_DIR }}
      shell: bash

    - name: Load cache
      id: cache_kubectl
      uses: actions/cache@v3
      with:
        path: ${{ inputs.CACHE_DIR }}
        key: kubectl-cache-${{ hashFiles('**/kubectl_version.txt') }}
        restore-keys: |
          kubectl-cache-

    - name: debug cachedir
      run: echo "CACHE_DIR is ${{ inputs.CACHE_DIR }}"
      shell: bash

    - name: curl kube
      if: steps.cache_kubectl.outputs.cache-hit != 'true'
      run: |
        sudo curl -fLo ${{ inputs.CACHE_DIR }}/kubectl https://dl.k8s.io/release/${{ inputs.KUBECTL_VERSION }}/bin/linux/amd64/kubectl
        sudo chmod +x ${{ inputs.CACHE_DIR }}/kubectl
        sudo cp ${{ inputs.CACHE_DIR}}kubectl /usr/bin/kubectl

      shell: bash

    - name: run kube
      run: |
        export PATH=${{ inputs.CACHE_DIR }}:$PATH
        which kubectl
      shell: bash
