name: 'composite action'
inputs:
  CACHE_DIR:
    description: 'aaa'
    required: true
    default: '/usr/cache/'
  KUBECTL_VERSION:
    description: 'aaa'
    required: true
    default: 'v1.22.17'

runs:
  using: 'composite'
  steps:
    - name: mkdir
      run: |
        sudo mkdir ${{ inputs.CACHE_DIR }}
        sudo touch ${{ inputs.CACHE_DIR }}kubectl
      shell: bash
    - name: debug cachedir
      run: echo "CACHE_DIR is ${{ inputs.CACHE_DIR }}"
      shell: bash
    - name: curl kube
      run: sudo curl -fLo ${{ inputs.CACHE_DIR }}kubectl https://dl.k8s.io/release/${{ inputs.KUBECTL_VERSION }}/bin/linux/amd64/kubectl
      shell: bash
    - name: run kube
      run: kubectl version
      shell: bash
