name: Main workflow
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: run composite action
          uses: ./.github/actions/composite-action
